### ISSUE TITLE
lonely pixel after nuclear winter :)

### ISSUE THREAD

**Issue by bocianu** [pkali/scorch_src#103]
![image](https://user-images.githubusercontent.com/2974998/177125320-4ceaf1fe-5cf4-47fb-97e8-bd1729953bb6.png)

there was one pixel left on the edge of the screen after nuclear winter.

**Comment by pkali** [comment]
INDERESTING!!!

**Comment by Pecusx** [comment]
I saw it several times during testing - I have no idea :)

**Comment by Pecusx** [comment]
I know that this is not a fix, but a workaround.
But it works! :)
