### ISSUE TITLE
Entering tank names using joystick

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#117]
Idea:
1. turn off the cursor
2. when HUMAN is selected, turn the cursor on and blink it.
3. then the joystick left-right moves the cursor, joystick up and down changes the letter.
4. fire ends editing

Problem - no way to name AI opponents. Consider turning on name edit after each opponent selection.

**Comment by ehn-pkalinowski** [comment]
Do it like this - long fire press activates the editor (up/down - letter, left/right - move cursor). Short fire - next screen.
Idea by Arek.

**Comment by Pecusx** [comment]
https://github.com/pkali/scorch_src/commit/dcdf5e6fc21a639c733b781bea8aadd0a4f3dff4
Done!
