### ISSUE TITLE
Texts wrapping at rightmost position (especially longer ones)

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#121]
Self explanatory. I'll try to catch it and place here (or maybe someone else? :) ).

**Comment by pkali** [comment]
easy to replicate with Hovercraft :]

**Comment by mikerro** [comment]
![image](https://user-images.githubusercontent.com/24191730/185732496-2b4e5f59-0bde-47bf-af32-92b0b999a97c.png)
Got it! Not only after death - all texts wrap as above (even longer names).

**Comment by pkali** [comment]
oh boy, it is fixed in 1.12 ;)
