### ISSUE TITLE
Death bug

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#122]
Sometimes tank "to be dead" flickers instead of exploding (and remains in this state).
Attached Atirra save-state. Tested on rightmost posiion. [death bug.zip](https://github.com/pkali/scorch_src/files/9387877/death.bug.zip)

**Comment by Pecusx** [comment]
There was tank fall bug.
Fixed! 

https://github.com/pkali/scorch_src/commit/c7e87c67ec91b9f0f4af4c2fcbe454dd67ae8ee0
