### ISSUE TITLE
Shield stays on screen after using "white flag" by player

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#138]
Like here: ![shield_bug](https://user-images.githubusercontent.com/24191730/192059880-efaddf17-c4ef-463e-b582-3a76a1a8d074.png)
IMHO it should crumble down.

**Comment by Pecusx** [comment]
I try to reproduce it and nothing.....

**Comment by Pecusx** [comment]
This only happened with computer players.
Very rare!

Fixed!
