### ISSUE TITLE
Glitch when using funkybomb next to screen edge

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#139]
![funkybomb bug2](https://user-images.githubusercontent.com/24191730/192112146-118196c5-6a4c-41e8-b760-0a523638d167.png)
Not sure if with wrap screen on or not but ground doesn't drop down in first/last screen column.

**Comment by Pecusx** [comment]
Please explain this in more detail. I am trying to reproduce it and nothing.

**Comment by Pecusx** [comment]
Fixed!
