### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by brad-colbert** [pkali/scorch_src#2]
Hello,

It looks like the source code is missing atari.hea and macro.hea.

**Comment by polluks** [comment]
examples/atari.hea is part of MADS.

**Comment by pkali** [comment]
Thank you guys for help, I am so happy you are looking at this little (but too big for me) code.
I've added missing files.

**Comment by brad-colbert** [comment]
That worked, thank you!  Built locally in my fork.  Hope I can spend some time to make this network enabled.
