### ISSUE TITLE
Add shields

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#20]
From [Probabilitydragon](https://atariage.com/forums/profile/74375-probabilitydragon/)

Shields are essential for the gameplay.

Right now there are 2 issues with it:
1. no real support for defensive weapons #11 
2. shields drawn on gfx screen would interfere with soil manipulation. 

Idea - do the shield using sprites.
Problem - Player 6 has got no sprite for themselves...

**Comment by ehn-pkalinowski** [comment]
idea - use 3 shaky missiles to rotate through potential 6 shields (with blinking).
it would look more like a force field, though...

**Comment by pkali** [comment]
OK, it will be a half-circle (a dome) over the tank.
Passed to execution.

**Comment by Pecusx** [comment]
Done!
