### ISSUE TITLE
RESET button hangs the game on AVGCART

### ISSUE THREAD

**Issue by KrzysRog** [pkali/scorch_src#29]
If the game runs from AVGCART it hangs after RESET pressed. This is probably related to the fact XEX'es are emulated without SIO. It still works ok on SIO2SD.

Maybe this could be fixed?

cheers,
Krzyś

**Comment by pkali** [comment]
can it be emulated in Altirra?

**Comment by pkali** [comment]
closing - the game is written as cleanly as possible, it works even on atari800 with 48KiB RAM, all OS versions we could get our hands on, we do not have AVGCART. Not possible to fix without further community input.
