### ISSUE TITLE
blinking color line due to a delayed DLI

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#31]
shell delay is done with STA WSYNC. It makes DLIs fire later. Must be fixed because there might be more DLIs in the future.

**Comment by pkali** [comment]
Haven't spotted it before because it is not visible in my daily driver emulator atari800. Thanks @phaeron

**Comment by Phaeron** [comment]
It’s a pleasure but did I do ? 😂

**Comment by pkali** [comment]
a different Phaeron apparently :)

**Comment by Phaeron** [comment]
Haha no problem
