### ISSUE TITLE
Human player gets omitted sometimes on first round.

### ISSUE THREAD

**Issue by bocianu** [pkali/scorch_src#47]
There are situations (not so rare) when in the first round **human** player gets omitted. 

When you play with 3 AI Tanks, they have 6 shoots before you can shoot your first missile - not fair ;)

**Comment by Pecusx** [comment]
You know....
Shit happens :)

**Comment by pkali** [comment]
Haven't yet been able to pin this one down. I think it happened to me a couple of times. Possibly code analysis is inevitable :(((((((((((((((((

**Comment by bocianu** [comment]
it still occurs in latest version. I played it yesterday for an hour, and it happened to me at least twice.

**Comment by mikerro** [comment]
It seems that player which gets hit just before his turn, gets omitted, regardless human or comp.

**Comment by pkali** [comment]
still no luck finding the solution. we'll be working on this.

**Comment by pkali** [comment]
this happens also for AI players.

**Comment by pkali** [comment]
Oh boy, I hope it is fixed. t'was tricky.
