### ISSUE TITLE
Seppuku doesn't kill tank in some instances

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#49]
When _Seppuku_ occurs, it doesn't kill tanks but damages it instead. Especially when it has lots of energy. Shouldn't it kill particular tank regardless of its energy amount?

**Comment by pkali** [comment]
This is a valid remark. Will address that.

**Comment by mikerro** [comment]
Instrumenty, które muszą być grane na 1 kanale:
- plasma blast 1 of 2 (08)
- dirt charge (0a)
- riot blast (11)

Pozostałe mogą być granę na 1 i na innych. :)




śr., 4 maj 2022 o 13:04 Pawel Kalinowski ***@***.***>
napisał(a):

**Comment by mikerro** [comment]
Dodane dirt charge small (takie małe "sypnięcie dirtem") - też 1st kanał
ONLY

oraz DIGGER - tu juz dowolnie. :)

Pozdro!

m.

śr., 4 maj 2022 o 17:01 Michał Szpilowski ***@***.***> napisał(a):

**Comment by Pecusx** [comment]
Ale oso chozi ? :)

**Comment by pkali** [comment]
fix'd 139
