### ISSUE TITLE
Add different wall effects

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#50]
What about adding some different wall effects just like PADDED, RUBBER and WRAP, and maybe SPRING just like in original game?

Link to manual (search: "Scorched Earth page 45" expression):
https://www.abandonwaredos.com/docs.php?sf=scorchedearthmanual.txt&st=manual&sg=Scorched+Earth&idg=1912

**Comment by Pecusx** [comment]
Done! :)
