### ISSUE TITLE
Build #139 - glitches after playing 1-2 rounds

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#55]
![scorch2](https://user-images.githubusercontent.com/24191730/167465281-a0a724b1-dd24-4f8b-a9f6-c492609ba6aa.png)
on player's panel

**Comment by mikerro** [comment]
Seems that it's gone after Pecus' patches. Let's close it for now.

**Comment by mikerro** [comment]
Sem that it happens despite newer build. Randomly just when drawing new screen.

**Comment by pkali** [comment]
OH SHITE IT WAS DIFFICULT
