### ISSUE TITLE
Sometimes there occur "multiple" purchases

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#56]
![scorch1](https://user-images.githubusercontent.com/24191730/167465717-ee306be9-4862-494f-95e2-1da173eee124.png)
LeapFrog weapon. It happened to me once when I bought some more expensive weapons. Can't replicate yet.

**Comment by pkali** [comment]
If anyone's could pin down when this happens, I'd be really happy - so far was unable to replicate, too.

**Comment by mikerro** [comment]
In fact, the game sometimes doesn't check you have ran out of particular weapon, and when you shoot having "0" of it, the counter goes to 55.

**Comment by Pecusx** [comment]
55 is 255 without 200 :)
In my opinion sometimes (somewere - I don'know were :) ) we decrease number of missiles, even though they are not bullets.
I added an additional check on DecreaseWeapon proc.
