### ISSUE TITLE
MIRV loops

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#6]
Observed MIRV loops - it shoots and shoots MIRV all over the screen. Very rare.

**Comment by bocianu** [comment]
Yes - But not so rare. I had it at least twice on my 5-6 games played on version 132
It even causes mirvs exploding on bottom of the screen, and causes total mayhem.

![image](https://user-images.githubusercontent.com/2974998/160485844-bcaee97f-a724-4023-95a1-3e7d53178148.png)

**Comment by pkali** [comment]
tried for hrs to trigger this issue. any hint how to replicate most welcome

**Comment by pkali** [comment]
[mirv_havoc.zip](https://github.com/pkali/scorch_src/files/8459238/mirv_havoc.zip)
got it, Atari800 save state incl.

**Comment by pkali** [comment]
oh boy, this one was difficult!
