### ISSUE TITLE
empty list of Defensives gets corrupted

### ISSUE THREAD

**Issue by bocianu** [pkali/scorch_src#62]
In the shop, when you switch to defensives but you can not afford one, the list is empty.
That is perfectly ok.
But you can still navigate down the list, and even go out of screen on the bottom edge.
Screen gets corrupted and so on... 

![image](https://user-images.githubusercontent.com/2974998/168674988-176ecc8e-a4db-4cee-a2f3-cc5a7b199585.png)

**Comment by pkali** [comment]
oh noes, the screen crosses the 4KiB barrier...

**Comment by pkali** [comment]
Not the best fix in the world, I've added a new defense 'White Flag' that right now cannot be bought, because of HONOR!
