### ISSUE TITLE
Different tank shapes, better barrels

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#64]
Is it possible to have some different tank shapes? Looking for volunteers,

**Comment by pkali** [comment]
Tank shapes are defined in this file: https://github.com/pkali/scorch_src/blob/master/artwork/tanks.fnt
The barrel must stay as it is - adjusting it was a pain in the bottom.
So it seems that only two lines of a character are really editable (16 pixels).
I think a creative soul could redefine 3 lines, just taking care of the barrel position above.
Then we could get e.g. 5 lines from the existing characters, 3 bottom ones from a new shape.
THe shapes must be left and right and include a mask in the consecutive char.

**Comment by pkali** [comment]
After meticulous analysis we know that it can and should be done with help of @6502adam
