### ISSUE TITLE
New weapon request: "Punch"

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#68]
It may work when two tanks are placed next to each other. Not much damage as itself but you can "punch" opponent some pixels away to make it fall into the chasm (and say "bye bye"). Could be graduated as Baby Punch, Punch and Heavy Punch and the heavier it is the more damage is given and the stronger "kick" as well (by more pixels, I meant).

**Comment by mikerro** [comment]
Bump (requested). :)

**Comment by Pecusx** [comment]
Done!
