### ISSUE TITLE
Selecting "Poolshark" or "Shooter" sometimes cause Force issues

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#70]
Sometimes games doesn't check Energy and doesn't limit Force, just like on the attached screenshot.
![scorch](https://user-images.githubusercontent.com/24191730/169118950-3f9cfb1b-a6fb-40ca-8c33-238fb31f4fa2.png)

It could be turned intro feature, though. :)

**Comment by pkali** [comment]
good catch :)

**Comment by mikerro** [comment]
Altirra (v3.90) save state of that issue. Player Jenna (Shooter, Red).

**Comment by pkali** [comment]
[state.atstate2.zip](https://github.com/pkali/scorch_src/files/8757048/state.atstate2.zip)

**Comment by mikerro** [comment]
It's more likely that Shooter has these issues now. Poolshark seems to act correctly.

**Comment by pkali** [comment]
Ha, fixed :)

**Comment by pkali** [comment]
not yet

**Comment by pkali** [comment]
Oh shi, encountered JMP (INDIRECT) 6502 bug here... must think of a solution...

**Comment by pkali** [comment]
finally.... was harder than it should.
