### ISSUE TITLE
Tanks stay unaffected by bullets

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#71]
Don't remember how it looks in original game but when you fire bullet and it goes straight to the tank (not ground below it), then perticular tank remains unaffected.

**Comment by pkali** [comment]
This is true. Collisions are detected with the ground only (excl. Laser). It must stay this way, but I'll move it to the 'enhancement' category. Will revisit.

**Comment by Pecusx** [comment]
Thanks to the new CheckCollisionWithTank procedure, the problem shouldn't be a problem anymore.
