### ISSUE TITLE
Minor screen glitches when changing screens

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#72]
Seems that screen-blanking is either missing, or there's wrong timing of it.

**Comment by pkali** [comment]
Pls. specify between which screens exactly? If between rounds on the main game view - it is possibly clearing the screen and can be masked. I am not seeing other glitches right now (on emulators).

**Comment by mikerro** [comment]
Ok, there's small "blink" when you start game, or right after leaving the shop. Right before screen re-drawing.

**Comment by mikerro** [comment]
It seems OK now. :)
