### ISSUE TITLE
"Fast-forward" mode

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#73]
My proposal is to add "fast-forward" mode.
What for? For example when player dies while playing agains computer players, pressing fast-forward will cause faster ending of round.

**Comment by pkali** [comment]
acktchually, this would be useful for debugging, too :]
moved to high priority :]

**Comment by pkali** [comment]
OK, pressing [START] speeds up everything that was possible to speed up. Unfortunately, most procedures work at the native speed, that is cannot be sped up without serious modifications. All explosions, soil fall, and even the falling of the tank and rotating of the barrel are drawn as quickly as possible.
Still, there is some substantial speed up, so let's call it a win.
