### ISSUE TITLE
No exit to title/menu

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#74]
Plaese add something like exit to title/menu.
It's more than missing. Could be with confirmation.

**Comment by pkali** [comment]
No quitting from the game yet, but started the jam and now you can return to the previous menu with [ESC]

**Comment by pkali** [comment]
when AIs are playing you need to hold [ESC] for a few seconds, but changing it to an immediate action would require a complete rewrite of many routines. For HUMAN players quitting it possible when aiming.
