### ISSUE TITLE
Dynamic power & angle control

### ISSUE THREAD

**Issue by 6502adam** [pkali/scorch_src#75]
Sometimes it takes quite a long time to adjust the power. I suggest that when player constantly holds the same direction of the joystick, the power change interval increases, i.e. that it jumps first by 1, then by 2, 3, etc.
Similarly, such a modification of the controls can be introduced when rotating the barrel (for consistency).

**Comment by mikerro** [comment]
Seems similar to #54

**Comment by pkali** [comment]
Angle fix when #87 done.

**Comment by pkali** [comment]
How it works - when you press joystick up (down) it is adding 1, but when you hold for 1/2s it starts adding 10.
After 2.5s it returns to adding 1 again, because this was easier and you are in the top force levels anyway.
