### ISSUE TITLE
using too many parachutes

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#8]
when a parachute is on and the tank dies (e.g. hit by a powerful
     weapon) the dead (invisible) tank falls with a parachute
     (and uses one parachute more than necessary)

**Comment by bocianu** [comment]
This one is pretty annoying. On my last game I lost all my parachutes in one turn - being dead from the first shot :) 
11k wasted.

Anyway this game is pretty addictive and enjoyable already, thanks!
Keep up the good work!

**Comment by Pecusx** [comment]
Now we have a different method to launch the parachute.
