### ISSUE TITLE
Save a page by removing WhereToSlideTable

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#81]
WhereToSlideTable is almost empty and can be replaced by a few "if's". Do this only when memory is really tight.

**Comment by Pecusx** [comment]
After a quick analysis...
In my opinion a "few" "if's" will be longer than the table. Simply - there must be many more "if's".
Table is more elegant and simple to correct/change.

**Comment by pkali** [comment]
ok, I agree. when we are really tight I might revisit.
