### ISSUE TITLE
Add ending to the game

### ISSUE THREAD

**Issue by pkali** [pkali/scorch_src#9]
The game has no end!!! Add ending!!!
A good idea for an ending - a TIP pic - Red Army taking Berlin :)
Another - vector tanks like in BattleZone
Another - stickman tankmen

**Comment by pkali** [comment]
Better idea - summary of the shenanigans
narrow screen
| tank name | big_points | cash | direct_hits | total_energy_gain (small points)

(direct_hits get from hitflag (1-6) means that tank was hit)

**Comment by pkali** [comment]
finally a doable idea 
IT'S RAINING TANKS, HALLELUJAH
IT"S RAINING TANKS

**Comment by Pecusx** [comment]
Done!
