### ISSUE TITLE
Possible Funky Bomb bug

### ISSUE THREAD

**Issue by mikerro** [pkali/scorch_src#92]
After exploding (especially on greater range), on drawn lines there appears some kind of gap (like text consinsing of spaces)
![scorch-fbomb](https://user-images.githubusercontent.com/24191730/172895294-8072b7fd-f93a-4eb0-aef2-8d106003a788.png)
it appears just before fb's traces go down

**Comment by Pecusx** [comment]
@pkali Maybe clear defensive message, before exploding, but after flight?

**Comment by pkali** [comment]
yes, for a reason I do not remember now we are clearing offensive texts twice or trice in some cases. Looking.

**Comment by pkali** [comment]
OK, it is deleted twice and the reason is that during FUnkybomb (and leapfrog) the landslide routine is running and the texts look funny. thinking.
