### ISSUE TITLE
Tank number 6 is falling faster.

### ISSUE THREAD

**Issue by Pecusx** [pkali/scorch_src#98]
This is not a significant bug.
Tank number 6 is falling faster than the other tanks.
I think it's a problem with the PM graphics. Tank number 6 is without PM.

**Comment by pkali** [comment]
yes, this is due to lack of PM. Will fix itself when we switch to 6 sprites :)

**Comment by Pecusx** [comment]
Now we switched to 6 sprites.
Done!
